#! Copyright IBM Corp. All Rights Reserved.
#!
#! SPDX-License-Identifier: Apache-2.0

#@ load("@ytt:data", "data")
#@ config = data.values
#@ peerUniquePort = 31000
#@ for i in range(0, len(config.peer_organizations)):
#@   organization = config.peer_organizations[i]
#@   for j in range(0, organization.num_ca):
---
kind: Service
apiVersion: v1
metadata:
  labels:
    k8s-app: #@ "ca{}-{}".format(j, organization.name)
  name: #@ "ca{}-{}".format(j, organization.name)
spec:
  selector:
    k8s-app: #@ "ca{}-{}".format(j, organization.name)
  type: #@ config.k8s.service_type
  ports:
    - name: port1
      port: 7054
#@   end
#@   for j in range(0, organization.num_peers):
---
kind: Service
apiVersion: v1
metadata:
  labels:
    k8s-app: #@ "peer{}-{}".format(j, organization.name)
  name: #@ "peer{}-{}".format(j, organization.name)
spec:
  selector:
    k8s-app: #@ "peer{}-{}".format(j, organization.name)
  type: #@ config.k8s.service_type
  ports:
    - name: port1
      port: #@ peerUniquePort
#@    if config.k8s.service_type == "NodePort":
      nodePort: #@ peerUniquePort
#@    end
    - name: port2
      port: 9443
#@   peerUniquePort += 1
#@ end
#@ end
#@ num_ordererOrgs = len(config.orderer_organizations)
#@ ordererUniquePort = 30000
#@ for i in range(0, num_ordererOrgs):
#@   organization = config.orderer_organizations[i]
#@   num_orderers = organization.num_orderers
#@ for j in range(0, organization.num_ca):
---
kind: Service
apiVersion: v1
metadata:
  labels:
    k8s-app: #@ "ca{}-{}".format(i, organization.name)
  name: #@ "ca{}-{}".format(i, organization.name)
spec:
  selector:
    k8s-app: #@ "ca{}-{}".format(i, organization.name)
  type: #@ config.k8s.service_type
  ports:
    - name: port1
      port: 7054
#@ end
#@ for j in range(0, num_orderers):
---
kind: Service
apiVersion: v1
metadata:
  labels:
    k8s-app: #@ "orderer{}-{}".format(j, organization.name)
  name: #@ "orderer{}-{}".format(j, organization.name)
spec:
  selector:
    k8s-app: #@ "orderer{}-{}".format(j, organization.name)
  type: #@ config.k8s.service_type
  ports:
    - name: port1
      port: #@ ordererUniquePort
#@    if config.k8s.service_type == "NodePort":
      nodePort: #@ ordererUniquePort
#@    end
    - name: port2
      port: 8443
#@    ordererUniquePort += 1
#@ end
#@ end

#@ if config.orderer.orderertype == "kafka":
#@   for i in range(0, config.kafka.num_kafka):
---
kind: Service
apiVersion: v1
metadata:
  labels:
    k8s-app: #@ "kafka{}".format(i)
  name: #@ "kafka{}".format(i)
spec:
  selector:
    k8s-app: #@ "kafka{}".format(i)
  ports:
    - name: port1
      port: 9092
    - name: port2
      port: 9093
#@   end
#@   for j in range(0, config.kafka.num_zookeepers):
---
kind: Service
apiVersion: v1
metadata:
  labels:
    k8s-app: #@ "zookeeper{}".format(j)
  name: #@ "zookeeper{}".format(j)
spec:
  selector:
    k8s-app: #@ "zookeeper{}".format(j)
  ports:
    - name: port1
      port: 2888
    - name: port2
      port: 3888
    - name: port3
      port: 2181
#@   end
#@ end